### ISSUE TITLE
Unable to use arrow function - stucked at Step 3

### ISSUE THREAD

**Issue by zulhfreelancer** [idanwe/meteor-whatsapp#1]
I'm following your [tutorial](http://info.meteor.com/blog/whatsapp-with-meteor-angular-and-ionic). But I got stucked in step #3 inside the `server/bootstrap.js` file.

This is my `server/bootstrap.js` file:

```
Meteor.startup(function() {
    if (Chats.find().count() === 0) {
        Messages.remove({});

        var messages = [{
            text: 'You on your way?',
            timestamp: moment().subtract(1, 'hours').toDate()
        }, {
            text: 'Hey, it\'s me',
            timestamp: moment().subtract(2, 'hours').toDate()
        }, {
            text: 'I should buy a boat',
            timestamp: moment().subtract(1, 'days').toDate()
        }, {
            text: 'Look at my mukluks!',
            timestamp: moment().subtract(4, 'days').toDate()
        }, {
            text: 'This is wicked good ice cream.',
            timestamp: moment().subtract(2, 'weeks').toDate()
        }];

        messages.forEach(m => { // this is the line 22
            Messages.insert(m);
        });

        var chats = [{
            name: 'Ethan Gonzalez',
            picture: 'https://randomuser.me/api/portraits/thumb/men/1.jpg'
        }, {
            name: 'Bryan Wallace',
            picture: 'https://randomuser.me/api/portraits/thumb/lego/1.jpg'
        }, {
            name: 'Avery Stewart',
            picture: 'https://randomuser.me/api/portraits/thumb/women/1.jpg'
        }, {
            name: 'Katie Peterson',
            picture: 'https://randomuser.me/api/portraits/thumb/women/2.jpg'
        }, {
            name: 'Ray Edwards',
            picture: 'https://randomuser.me/api/portraits/thumb/men/2.jpg'
        }];

        chats.forEach(chat => {
            let message = Messages.findOne({
                chatId: {
                    $exists: false
                }
            });
            chat.lastMessage = message;
            let chatId = Chats.insert(chat);
            Messages.update(message._id, {
                $set: {
                    chatId: chatId
                }
            });
        });
    }
});
```

This is the error I got from my Sublime Text:

![screen shot 2015-10-17 at 11 10 06 pm](https://cloud.githubusercontent.com/assets/3416976/10559428/2fe3b5d0-7523-11e5-8ef8-d52986ca6537.png)

And this is the error I got at the browser:

![screen shot 2015-10-17 at 11 15 11 pm](https://cloud.githubusercontent.com/assets/3416976/10559460/b1c0bc10-7523-11e5-9333-211ca35433c4.png)

What should I do now?

[This](https://github.com/zulhfreelancer/whatsapp_meteor/commit/aa0f0cdaabef7f334ed7ec937f056eb4fb1105ed) is my last commit for that.

**Comment by Urigo** [comment]
What version of Meteor are you using?

**Comment by zulhfreelancer** [comment]
I'm using `1.2.0.2` version.

![screen shot 2015-10-18 at 1 01 05 am](https://cloud.githubusercontent.com/assets/3416976/10560082/7ec56194-7532-11e5-87e5-5f64528db8a6.png)

**Comment by idanwe** [comment]
You need to update your packages to meteor 1.2.0.2, run `meteor update` in your project.

This are the desired packages - https://github.com/idanwe/meteor-whatsapp/blob/master/.meteor/packages
In contrast to yours packages file - https://github.com/zulhfreelancer/whatsapp_meteor/blob/master/.meteor/packages

Feel free to reopen if it will not solve the problem
