### ISSUE TITLE
How to connect with external server

### ISSUE THREAD

**Issue by programming-kid** [idanwe/meteor-whatsapp#2]
I am fairly new to meteor and to me it seems 99% magic & 1% `javascript`. 

 In the entire tutorial i didn't find the connection url so i assume both the server & ionic app are running on `localhost` but then how will it work when meteor is say on  ec2 host and app is on play store. 

How to connect ionic app to meteor on external server ??

I am surely missing something here 
Pls help

**Comment by idanwe** [comment]
When you are using the meteor build for android or ios, meteor sets the url for the DDP connection.

Take a look at:
- [angular meteor tutorial](http://angular-meteor.com/tutorials/angular1/running-your-app-on-android-or-ios-with-phoneGap)
- [meteor toturial](https://www.meteor.com/tutorials/blaze/running-on-mobile)

**Comment by programming-kid** [comment]
thanks @idanwe
