### ISSUE TITLE
Wrong number?

### ISSUE THREAD

**Issue by vapits** [idanwe/meteor-whatsapp#4]
![image](https://cloud.githubusercontent.com/assets/8594758/11244757/8fd1d350-8e0f-11e5-8338-f993e73b6dbd.png)

This is my settings.json:

``` javascript
{
  "TWILIO": {
    "FROM": "meteor-whatsapp",
    "SID": "",
    "TOKEN": ""
  },
  "ACCOUNTS_PHONE": {
    "ADMIN_NUMBERS": ["123456789", "987654321"],
    "MASTER_CODE": "1234"
  }
}
```

**Comment by erezcarmel** [comment]
The okland:accounts-phone package requestPhoneVerification method requires phone number with country code, prefix and the number, for example: +972545545454.
You can find the explanation in section 4.2 of the tutorial.

**Comment by vapits** [comment]
It never worked but I had left it so I close this one.
