### ISSUE TITLE
Stuck at 'Sending verification code' when running on a device

### ISSUE THREAD

**Issue by abtx** [idanwe/meteor-whatsapp#9]
The app gets stuck there, I assume that the phone verification is just a means to create unique user account (so it shouldn't matter what phone number I enter as it's valid). It gets stuck there tho. Is this anything to do with database when running off localhost on a mobile phone?

**Comment by idanwe** [comment]
@abtx this repo doesn't work with the latest meteor and angular-meteor.

So try the latest version at https://github.com/Urigo/Ionic-MeteorCLI-WhatsApp.

I will close it for now,
If you need to use this version please reopen the issue and provide code sample / the step for reproduce the error.

**Comment by abtx** [comment]
Thanks @idanwe, actually I did get it running. My phone's WIFI was off. But thanks to the pointer to the more up to date version. Cheers!
